version: "3.5"
services:
  drss-redis:
    container_name: drss-redis-container
    image: redis:alpine
    # Uncomment below to hide redis logs
    # logging:
    #   driver: none
    networks:
      - drss-network
  drss-web:
    container_name: drss-web-container
    restart: on-failure:10
    build: .
    ports:
      - "8081:8081"
    networks:
      - drss-network
    environment:
      - DRSSWEB_BOT_TOKEN=drss_docker_token
      - DRSSWEB_DATABASE_URI=mongodb://drss-mongo:27017/rss
      - DRSSWEB_DATABASE_REDIS=redis://drss-redis:6379

networks:
  drss-network:
    name: drss-network
